#  ⡤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⣤⣤⡤⣤⣤⣤⣤⣤⣤⣤⣤⢤⠤⢤⣤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⢤⡼⠋⠀⠀⢀⡴⠋⠀⠀⢠⡇⠀⠀⠀⠀⠀⡾⠀⠀⠀⠀⠳⡄⠀⠀⠀⠨⢷⡤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤
# ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡟⡻⣽⣿⣿⣿⣿⣿⡯⢿⣿⣿⣾⣫⢟⣻⠃⠁⠁⠀⠀⠀⠀⠀⠀⠀⠀⠠⢀⣴⣟⡴⠁⠀⠤⠤⢠⡞⠀⠀⠀⢀⣼⡇⠀⠀⠀⠀⢠⡇⣶⡀⠀⠀⠀⠹⡄⠀⠀⠀⢦⠀⢻⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⢀⣀⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⢀⡀⠉⠉⠋⠉⠉⠉⣽⡟⢁⣨⣟⣽⢫⣺⠽⣴⣶⡆⠀⠀⠀⠀⠀⠀⠀⠀⡰⣀⣶⢫⡏⡾⠀⠀⠀⡞⠀⢀⡀⢀⡞⢹⡁⠀⠀⠀⠀⢸⢹⠋⢷⡀⠀⠀⠀⢹⡀⠀⠀⠘⡇⠀⢻⣖⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⢸⣿⣿⠛⢣⣄⠀⣠⡄⣠⣤⣄⢸⣿⢀⣄⠀⠀⠀⣸⠟⠀⡞⠟⠟⠀⠘⠚⣿⡟⠛⠁⠀⠀⠀⠀⠀⠀⠀⠀⠘⠉⢀⡟⣼⠁⠀⠀⢸⠁⠀⡾⢠⣟⣦⢼⡇⢇⠀⠀⠀⣸⣿⣄⡈⢷⡀⠀⠀⠀⣇⠀⠀⠀⢻⠘⡏⢧⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⢸⡟⠛⠀⢿⣿⠀⣿⣿⣿⠛⣻⣿⣿⣿⡏⠀⠀⢰⡟⠋⠀⠀⣀⣤⣤⣶⣲⠛⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⢣⡇⠀⠀⠀⡏⠀⣸⢣⡟⠉⠀⠘⡇⡟⣆⠀⠀⣿⠁⠐⠉⠻⢧⠀⠀⠀⢸⠀⠀⠀⢸⡇⠀⠀⣷⠃⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠸⠇⠀⠀⠘⠿⠿⠿⠟⠿⠿⠿⠻⠿⠻⠷⠀⢀⡟⠌⠀⠀⠀⢿⣟⡿⣿⣹⠃⠀⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣯⢿⠀⠀⠀⠀⡇⢰⣟⡟⠀⠀⠀⠀⢿⠃⠈⠣⡁⡏⠀⠀⠀⠀⠈⢧⠀⠀⢸⠀⠀⠀⠸⡇⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⣤⡄⠀⢀⣤⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⠫⠀⠀⠀⠀⠈⠀⢠⣧⠧⢤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠁⢸⢠⠀⠀⠀⣇⡏⡟⠀⠀⣀⡤⠄⠀⠀⠀⠈⠈⠣⠀⢠⣀⡀⠀⠈⢧⠀⢸⠀⠀⠀⢀⡇⠀⠀⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠻⣷⣶⣿⠿⣠⣤⣤⡄⢠⡄⠀⣠⣄⠀⣼⠃⠀⠀⠀⠀⠀⠀⠱⣶⣾⣿⣿⣇⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣸⡇⠀⠀⣿⠀⠁⣠⣶⣾⡿⠿⠖⠀⠀⠀⠀⠀⢾⣿⣷⣷⣤⣀⠈⢧⢸⠀⠀⠀⢸⡇⠀⢠⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⢸⣿⡇⢠⣿⠛⢻⣿⣿⡇⠀⣿⣿⠀⡳⣄⠀⠀⠀⠀⠀⠀⠀⠻⢻⣿⣿⠿⠃⠀⠀⠀⢀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠘⡿⢻⡀⠀⢸⣠⠾⠛⠉⠀⠀⠀⠀⠀⠤⠀⠀⠀⠀⠀⠀⠉⠙⠻⢷⡄⡏⠀⠀⠀⢸⠁⠀⣸⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⠸⣿⠇⠈⠻⠿⠿⠟⠙⢿⣿⣿⡏⠀⠀⠈⠳⣔⠀⠀⠀⠀⠀⠂⢠⣿⡿⠀⠀⠀⠀⣴⢾⢹⡿⡅⠀⠀⠀⠀⠀⠀⠀⠀⢠⢷⡀⢸⡇⢐⣠⣴⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣲⡠⣤⣠⠀⡼⠁⠀⠀⠀⣾⡆⠀⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣮⠷⠀⠀⠀⠀⠀⢹⢸⠁⠀⠀⠀⢐⣟⢸⢸⠇⡇⠀⠀⠀⠀⠀⠀⠀⢀⡟⢸⠛⢦⣧⠻⠟⠛⠉⠀⢀⣴⣾⣿⣿⣿⣿⣶⣆⠙⠛⠛⣛⡽⢁⡬⠞⠡⢰⣿⡇⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡞⠫⠟⠀⠀⠀⠀⠀⠀⠀⡼⣿⡆⠀⠀⠀⣿⢸⣾⢸⡆⢳⡖⢦⠀⠀⠀⠀⢠⡟⠀⣼⠀⠀⡏⠀⠀⠀⠀⠀⢸⣿⣿⣿⣽⣿⣯⣿⣿⠀⠀⠠⠾⢛⡿⠐⠀⠀⣾⡾⠁⢨⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡏⣇⠀⠀⢰⡇⣿⢸⢀⣧⠈⡇⠘⣆⠀⠀⣱⠋⠈⢠⡏⠀⠀⢳⡄⠀⠀⠀⠀⠀⠻⣿⢿⣿⣿⢿⡷⠃⠀⠀⠀⢀⡞⠀⠀⠀⢰⠋⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣇⠀⠀⠀⠀⠀⠀⠀⣀⡼⣿⣿⣥⠂⢹⡇⣿⠘⠇⠈⠀⣹⠄⢹⣤⠞⠁⠀⢠⡾⠀⠀⠀⣸⣿⡮⣄⠀⠀⠀⠀⠈⠉⠉⠉⠁⠀⠀⠀⣀⣴⡿⠀⠀⠀⢠⣿⠀⠀⢠⡏⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⡀⠀⠀⠀⠀⠀⠘⢣⡳⣎⠒⣫⣄⠘⡇⠘⠀⠀⠀⢀⠎⠀⠀⡇⡀⢀⡴⣻⠃⠀⠀⢰⣿⣾⢿⣿⣿⣶⣦⣤⣄⣀⣀⣠⣤⣴⢶⣿⣳⡿⠁⠀⠀⠀⣾⡇⠀⠀⣼⢸⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣇⠀⠀⠀⠀⠀⠀⠀⠙⣾⣿⠷⠋⠀⢷⠀⠀⠀⠀⡎⠀⠀⠀⣿⣿⠉⣰⠇⠀⠀⢀⣟⣿⣳⣿⣿⣿⣿⣿⣯⣿⣿⣿⣽⣿⣿⣿⢿⡿⠁⠀⠀⠀⣸⣽⡀⠀⢠⠇⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⡀⠀⠀⠠⣔⡤⠈⢻⠟⠁⠁⠀⡀⣿⣧⠀⠀⠀⠃⠀⠀⣰⣿⣿⢠⠏⠀⠀⠀⣸⠉⠉⠁⠘⢿⣿⣿⣿⣿⣿⣻⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⢠⠷⢺⣭⢷⣯⣆⢸⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⢀⣤⢤⡀⠀⠀⠀⠀⠀⠀⢀⡴⣤⣄⡀⠀⠀⠘⣇⠀⠀⢸⣿⣧⣴⣀⣡⣤⣤⣾⣾⣿⣿⣧⠀⠀⢈⣵⣿⣿⣿⣿⠏⠀⠀⠀⠀⣯⢳⡀⠀⠀⠀⠙⠿⣿⣿⣻⣿⣿⣿⣿⣿⣷⠇⠀⠀⠀⠀⣾⢶⣯⣾⣿⢛⣛⠛⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⣒⠒⠒⢲⠀⠀⠀⣿
# ⣇⡴⠞⠋⠀⠀⢿⣤⠀⠀⠀⢀⡴⠛⠋⠀⠈⠙⠛⠶⢤⣿⡄⠀⠸⠳⠟⢳⠦⣤⣀⣘⣿⣿⣿⣿⣿⣟⡶⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⢸⣿⣷⡻⣄⡀⠀⠀⠀⠀⣙⡏⣫⠟⠛⠋⢩⡏⣰⠀⠀⠀⢰⣷⣿⣿⣿⣿⢸⣿⠀⠀⠀⢠⡶⠶⢦⡀⢰⡶⠿⣶⡄⣾⣟⠛⠛⠃⢸⠀⠀⠀⣿
# ⡏⠀⠀⠀⠀⠀⠈⢺⣷⣄⣴⠛⠃⠀⠀⠀⠀⠀⠀⠀⠀⠈⠁⠀⠀⠀⠀⠸⠇⠄⠀⢀⡵⢛⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⣿⢸⣿⣿⣿⣮⡳⣄⣠⡴⣞⡽⠛⡻⣟⢦⣀⣼⢁⡏⠀⠀⠀⣾⣿⣿⣿⣿⣿⢠⣿⣤⣤⣤⠸⣧⣤⣼⠇⠘⠿⣶⣿⡧⣭⣭⣽⣷⠀⢸⠀⠀⠀⣿
# ⡇⠀⠀⠀⠀⠀⠀⠉⠉⠉⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⠎⠀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⣿⢸⣿⣿⣿⣿⡍⠲⠖⣺⣿⠰⣿⡗⢸⣵⢯⡏⣸⡇⠀⠀⠀⡟⢻⣿⣿⣿⣿⣤⣤⣤⣤⣤⣤⣤⣤⣤⢤⣿⣿⣿⣿⣧⣤⣭⣥⣴⣤⡼⠀⠀⠀⣿
# ⠧⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠴⠷⠶⠶⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠶⠶⠦⠿⠿⠿⠿⠿⠿⠿⠶⠶⠿⠷⠶⠶⠶⠾⠿⠾⠷⠿⠷⠶⠶⠶⠿⠾⠮⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠶⠶⠶⠶⠶⠶⠶⠶⠶⠶⠶⠶⠶
#两个数据库都要配置,不然用不了!
spring:
  #MySQL
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nyanid?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: nyanid
    password: nyanid
  data:
    #Redis
    redis:
      host: localhost
      database: 0
      password: nyanid123
      port: 6379
      #邮件服务,必须配置!
  mail:
    host: smtp.yeah.net #SMTP 服务器地址
    port: 25 #SMTP 服务器端口
    username: bjdbjd@bjdbjd.net #邮箱名
    password: bjdbjd #邮箱密码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false

#服务器配置
server:
  port: 8080
  address: localhost

#NyanID配置
NyanidSetting:
  allowedOriginPatterns: "https://*.*.*:*" #匹配所有 example.com 域名及其端口号
  EnableCommand: true #是否启用控制台指令
  EnableUserRegister: true #是否启用用户注册
  # IP访问限制(仅适用于authserver)
  MAX_REQUESTS_PER_SECOND: 6 #IP访问频率限制
  TIME_FRAME_IN_MILLISECONDS: 9500 #IP访问时间间隔
  encryptionKey: | #用户密码加密密钥(改了过后就不要改了!)
    JSJna98sdb7DAGBUG
    gd87TAD87T8AGD8t6
    87D567S567D5578ds6
    7d57SDd76TS67DT786
    S78d678678S6786cvg3
    cf4gfv67T6DSGVUhguGU
    YGgduysgUY34HJV2JH3
    4GGduygDTTS8F9Tgd5
    64EDW65F6WER54T6541
    SDF4EW6T541S33d1f3w
    e464464FG64WE6R54G3
    214T1S1AF454654ge4r6
    4FEH4E498T32D4GSK43
  HOST: "http://nyanid.cn:8080" #前端域名,注册时候发给用户验证邮件需要使用,因为API服务器需要隐藏真实IP,后端会默认给链接后面加上/verification/,所以链接后面不需要带 /
  qqbot: #QQ机器人
    isEnable: false
    appid: "qqqqq"
    token: "qqqqqqqq"
    secret: "qqqqqqq"
    isSandbox: true #是否启用沙盒模式
  ContactEmail: "neko@nyacat.cloud" #邮箱,用户收到邮件Contact us的邮箱地址
  TeamName: "DecObfNeko Development Team" #团队名称
  msg: |
    诶多……☆是♡同♡类♡呢♡喵♪（由乃逆光捧脸.jpg）那群八嘎是不会懂的呀……关于「二次元の美好」♡呐，如果说吾の存在有意义的话、那一定是因为「二·次·元」吧☆？所以呢——妄图污染这份「爱」的人类、都会被吾「抹」「杀」「掉」喔♪（小声）嘛……讨厌二次元的八嘎三次元最恶心了啊魂淡！★,
    呐、二次元の民那……都·是·最·最·善·良·の·存·在·呐☆多洗忒……要「嘲笑」这样的孩子呢？吾辈不明白啊——？嘛……说到底，你们都只是污秽の「来自三次元的大人」吧？大人什么的、最·讨·厌·了★♪,
    啊嘞啊嘞QAQ？多洗忒……欧尼酱ww？呐、桥豆麻袋……已经「厌烦」吾辈了嘛？哼唧……真是「冷·酷·の·人」呢QuQ——☆(๑°⌓°๑)嘛……即便是这样的哇达西，一定也是有「存·在·の·意·义」的吧、内~★快来「肯定」啊？不然呀……咱可就要「黑化」了哦♪呐？#(太开心)  ,
    呐。。。（伸出的小手又迅速垂下去）嗦嘎（表情有点失落），米娜桑已经不喜欢了呀（紧咬嘴唇），得磨，米娜桑忘了当初吗（握紧小手），莫以得丝（强忍住眼泪），已经大丈夫了呦（挤出笑脸），瓦大喜瓦，滋多滋多，滋多滋多（语气越来越用力了）滋多戴斯给！！！一滋嘛叠磨瓦撕裂嘛赛！！！至死都不会瓦斯裂嘛斯（认真的表情）,
    诶多……看起来阁下对于「二·次·元」の理解、似·乎·满·是·谬·误·哦☆~！嘛，连最为基本の「礼♪义♪廉♪耻♪」都早已失去了啊……♪（笑）呐，我说啊——这样のkimino、也会有自称「二♡次♡元」の资格吗★？fufufu——说到底、阁下已经「二·次·元·失·格」了吧？呐~♪#(太开心)  ,
    唔噗噗~汝等「劣·等·生·物」......也配去「妄想」吗？呐、「真正的二次元」什么的— —吾辈看汝是一点都不懂啊☆ （笑）嘛嘛嘛......不过看着汝试图伪装成「二次元」の可笑姿态，倒是让吾辈对于「三·次·元·的·白·痴」稍微有了些许兴趣哦？★【图片】诶多……☆是♡同♡类♡呢♡喵♪（由乃逆光捧脸.jpg）那群八嘎是不会懂的呀……关于「二次元の美好」♡呐，如果说吾の存在有意义的话、那一定是因为「二·次·元」吧☆？所以呢——妄图污染这份「爱」的人类、都会被吾「抹」「杀」「掉」喔♪（小声）嘛……讨厌二次元的八嘎三次元最恶心了啊魂淡！★,
    呐、二次元の民那……都·是·最·最·善·良·の·存·在·呐☆多洗忒……要「嘲笑」这样的孩子呢？吾辈不明白啊——？嘛……说到底，你们都只是污秽の「来自三次元的大人」吧？大人什么的、最·讨·厌·了★♪,
    啊嘞啊嘞QAQ？多洗忒……欧尼酱ww？呐、桥豆麻袋……已经「厌烦」吾辈了嘛？哼唧……真是「冷·酷·の·人」呢QuQ——☆(๑°⌓°๑)嘛……即便是这样的哇达西，一定也是有「存·在·の·意·义」的吧、内~★快来「肯定」啊？不然呀……咱可就要「黑化」了哦♪呐？,
    呐。。。（伸出的小手又迅速垂下去）嗦嘎（表情有点失落），米娜桑已经不喜欢了呀（紧咬嘴唇），得磨，米娜桑忘了当初吗（握紧小手），莫以得丝（强忍住眼泪），已经大丈夫了呦（挤出笑脸），瓦大喜瓦，滋多滋多，滋多滋多（语气越来越用力了）滋多戴斯给！！！一滋嘛叠磨瓦撕裂嘛赛！！！至死都不会瓦斯裂嘛斯（认真的表情）,
    诶多……看起来阁下对于「二·次·元」の理解、似·乎·满·是·谬·误·哦☆~！嘛，连最为基本の「礼♪义♪廉♪耻♪」都早已失去了啊……♪（笑）呐，我说啊——这样のkimino、也会有自称「二♡次♡元」の资格吗★？fufufu——说到底、阁下已经「二·次·元·失·格」了吧？呐~♪,
    唔噗噗~汝等「劣·等·生·物」......也配去「妄想」吗？呐、「真正的二次元」什么的— —吾辈看汝是一点都不懂啊☆ （笑）嘛嘛嘛......不过看着汝试图伪装成「二次元」の可笑姿态，倒是让吾辈对于「三·次·元·的·白·痴」稍微有了些许兴趣哦？★【图片】诶多……☆是♡同♡类♡呢♡喵♪（由乃逆光捧脸.jpg）那群八嘎是不会懂的呀……关于「二次元の美好」♡呐，如果说吾の存在有意义的话、那一定是因为「二·次·元」吧☆？所以呢——妄图污染这份「爱」的人类、都会被吾「抹」「杀」「掉」喔♪（小声）嘛……讨厌二次元的八嘎三次元最恶心了啊魂淡！★,
    呐、二次元の民那……都·是·最·最·善·良·の·存·在·呐☆多洗忒……要「嘲笑」这样的孩子呢？吾辈不明白啊——？嘛……说到底，你们都只是污秽の「来自三次元的大人」吧？大人什么的、最·讨·厌·了★♪,
    啊嘞啊嘞QAQ？多洗忒……欧尼酱ww？呐、桥豆麻袋……已经「厌烦」吾辈了嘛？哼唧……真是「冷·酷·の·人」呢QuQ——☆(๑°⌓°๑)嘛……即便是这样的哇达西，一定也是有「存·在·の·意·义」的吧、内~★快来「肯定」啊？不然呀……咱可就要「黑化」了哦♪呐？#(太开心),





#Minecraft 外置登录服务器配置
yggdrasil:
  implementationName: "yggdrasil-TakanashiHoshino-server"
  implementationVersion: "0.0.1"
  serverName: "TakanashiHoshino Server" #服务器名称
  links-homepage: "https://skin.example.com/"
  links-register: "https://skin.example.com/register"
  feature-non_email_login: true
  signaturePublickey: | 
    -----BEGIN PUBLIC KEY-----
    MIICIj...（省略）...EAAQ==
    -----END PUBLIC KEY-----
    
