#  ⡤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⣤⣤⡤⣤⣤⣤⣤⣤⣤⣤⣤⢤⠤⢤⣤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⢤⡼⠋⠀⠀⢀⡴⠋⠀⠀⢠⡇⠀⠀⠀⠀⠀⡾⠀⠀⠀⠀⠳⡄⠀⠀⠀⠨⢷⡤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤
# ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡟⡻⣽⣿⣿⣿⣿⣿⡯⢿⣿⣿⣾⣫⢟⣻⠃⠁⠁⠀⠀⠀⠀⠀⠀⠀⠀⠠⢀⣴⣟⡴⠁⠀⠤⠤⢠⡞⠀⠀⠀⢀⣼⡇⠀⠀⠀⠀⢠⡇⣶⡀⠀⠀⠀⠹⡄⠀⠀⠀⢦⠀⢻⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⢀⣀⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⢀⡀⠉⠉⠋⠉⠉⠉⣽⡟⢁⣨⣟⣽⢫⣺⠽⣴⣶⡆⠀⠀⠀⠀⠀⠀⠀⠀⡰⣀⣶⢫⡏⡾⠀⠀⠀⡞⠀⢀⡀⢀⡞⢹⡁⠀⠀⠀⠀⢸⢹⠋⢷⡀⠀⠀⠀⢹⡀⠀⠀⠘⡇⠀⢻⣖⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⢸⣿⣿⠛⢣⣄⠀⣠⡄⣠⣤⣄⢸⣿⢀⣄⠀⠀⠀⣸⠟⠀⡞⠟⠟⠀⠘⠚⣿⡟⠛⠁⠀⠀⠀⠀⠀⠀⠀⠀⠘⠉⢀⡟⣼⠁⠀⠀⢸⠁⠀⡾⢠⣟⣦⢼⡇⢇⠀⠀⠀⣸⣿⣄⡈⢷⡀⠀⠀⠀⣇⠀⠀⠀⢻⠘⡏⢧⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⢸⡟⠛⠀⢿⣿⠀⣿⣿⣿⠛⣻⣿⣿⣿⡏⠀⠀⢰⡟⠋⠀⠀⣀⣤⣤⣶⣲⠛⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⢣⡇⠀⠀⠀⡏⠀⣸⢣⡟⠉⠀⠘⡇⡟⣆⠀⠀⣿⠁⠐⠉⠻⢧⠀⠀⠀⢸⠀⠀⠀⢸⡇⠀⠀⣷⠃⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠸⠇⠀⠀⠘⠿⠿⠿⠟⠿⠿⠿⠻⠿⠻⠷⠀⢀⡟⠌⠀⠀⠀⢿⣟⡿⣿⣹⠃⠀⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣯⢿⠀⠀⠀⠀⡇⢰⣟⡟⠀⠀⠀⠀⢿⠃⠈⠣⡁⡏⠀⠀⠀⠀⠈⢧⠀⠀⢸⠀⠀⠀⠸⡇⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⣤⡄⠀⢀⣤⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⠫⠀⠀⠀⠀⠈⠀⢠⣧⠧⢤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠁⢸⢠⠀⠀⠀⣇⡏⡟⠀⠀⣀⡤⠄⠀⠀⠀⠈⠈⠣⠀⢠⣀⡀⠀⠈⢧⠀⢸⠀⠀⠀⢀⡇⠀⠀⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠻⣷⣶⣿⠿⣠⣤⣤⡄⢠⡄⠀⣠⣄⠀⣼⠃⠀⠀⠀⠀⠀⠀⠱⣶⣾⣿⣿⣇⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣸⡇⠀⠀⣿⠀⠁⣠⣶⣾⡿⠿⠖⠀⠀⠀⠀⠀⢾⣿⣷⣷⣤⣀⠈⢧⢸⠀⠀⠀⢸⡇⠀⢠⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⢸⣿⡇⢠⣿⠛⢻⣿⣿⡇⠀⣿⣿⠀⡳⣄⠀⠀⠀⠀⠀⠀⠀⠻⢻⣿⣿⠿⠃⠀⠀⠀⢀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠘⡿⢻⡀⠀⢸⣠⠾⠛⠉⠀⠀⠀⠀⠀⠤⠀⠀⠀⠀⠀⠀⠉⠙⠻⢷⡄⡏⠀⠀⠀⢸⠁⠀⣸⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⠸⣿⠇⠈⠻⠿⠿⠟⠙⢿⣿⣿⡏⠀⠀⠈⠳⣔⠀⠀⠀⠀⠀⠂⢠⣿⡿⠀⠀⠀⠀⣴⢾⢹⡿⡅⠀⠀⠀⠀⠀⠀⠀⠀⢠⢷⡀⢸⡇⢐⣠⣴⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣲⡠⣤⣠⠀⡼⠁⠀⠀⠀⣾⡆⠀⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣮⠷⠀⠀⠀⠀⠀⢹⢸⠁⠀⠀⠀⢐⣟⢸⢸⠇⡇⠀⠀⠀⠀⠀⠀⠀⢀⡟⢸⠛⢦⣧⠻⠟⠛⠉⠀⢀⣴⣾⣿⣿⣿⣿⣶⣆⠙⠛⠛⣛⡽⢁⡬⠞⠡⢰⣿⡇⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡞⠫⠟⠀⠀⠀⠀⠀⠀⠀⡼⣿⡆⠀⠀⠀⣿⢸⣾⢸⡆⢳⡖⢦⠀⠀⠀⠀⢠⡟⠀⣼⠀⠀⡏⠀⠀⠀⠀⠀⢸⣿⣿⣿⣽⣿⣯⣿⣿⠀⠀⠠⠾⢛⡿⠐⠀⠀⣾⡾⠁⢨⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡏⣇⠀⠀⢰⡇⣿⢸⢀⣧⠈⡇⠘⣆⠀⠀⣱⠋⠈⢠⡏⠀⠀⢳⡄⠀⠀⠀⠀⠀⠻⣿⢿⣿⣿⢿⡷⠃⠀⠀⠀⢀⡞⠀⠀⠀⢰⠋⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣇⠀⠀⠀⠀⠀⠀⠀⣀⡼⣿⣿⣥⠂⢹⡇⣿⠘⠇⠈⠀⣹⠄⢹⣤⠞⠁⠀⢠⡾⠀⠀⠀⣸⣿⡮⣄⠀⠀⠀⠀⠈⠉⠉⠉⠁⠀⠀⠀⣀⣴⡿⠀⠀⠀⢠⣿⠀⠀⢠⡏⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⡀⠀⠀⠀⠀⠀⠘⢣⡳⣎⠒⣫⣄⠘⡇⠘⠀⠀⠀⢀⠎⠀⠀⡇⡀⢀⡴⣻⠃⠀⠀⢰⣿⣾⢿⣿⣿⣶⣦⣤⣄⣀⣀⣠⣤⣴⢶⣿⣳⡿⠁⠀⠀⠀⣾⡇⠀⠀⣼⢸⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣇⠀⠀⠀⠀⠀⠀⠀⠙⣾⣿⠷⠋⠀⢷⠀⠀⠀⠀⡎⠀⠀⠀⣿⣿⠉⣰⠇⠀⠀⢀⣟⣿⣳⣿⣿⣿⣿⣿⣯⣿⣿⣿⣽⣿⣿⣿⢿⡿⠁⠀⠀⠀⣸⣽⡀⠀⢠⠇⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⡀⠀⠀⠠⣔⡤⠈⢻⠟⠁⠁⠀⡀⣿⣧⠀⠀⠀⠃⠀⠀⣰⣿⣿⢠⠏⠀⠀⠀⣸⠉⠉⠁⠘⢿⣿⣿⣿⣿⣿⣻⣿⣿⣿⣿⣿⣿⠁⠀⠀⠀⢠⠷⢺⣭⢷⣯⣆⢸⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿
# ⡇⠀⠀⢀⣤⢤⡀⠀⠀⠀⠀⠀⠀⢀⡴⣤⣄⡀⠀⠀⠘⣇⠀⠀⢸⣿⣧⣴⣀⣡⣤⣤⣾⣾⣿⣿⣧⠀⠀⢈⣵⣿⣿⣿⣿⠏⠀⠀⠀⠀⣯⢳⡀⠀⠀⠀⠙⠿⣿⣿⣻⣿⣿⣿⣿⣿⣷⠇⠀⠀⠀⠀⣾⢶⣯⣾⣿⢛⣛⠛⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⣒⠒⠒⢲⠀⠀⠀⣿
# ⣇⡴⠞⠋⠀⠀⢿⣤⠀⠀⠀⢀⡴⠛⠋⠀⠈⠙⠛⠶⢤⣿⡄⠀⠸⠳⠟⢳⠦⣤⣀⣘⣿⣿⣿⣿⣿⣟⡶⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⢸⣿⣷⡻⣄⡀⠀⠀⠀⠀⣙⡏⣫⠟⠛⠋⢩⡏⣰⠀⠀⠀⢰⣷⣿⣿⣿⣿⢸⣿⠀⠀⠀⢠⡶⠶⢦⡀⢰⡶⠿⣶⡄⣾⣟⠛⠛⠃⢸⠀⠀⠀⣿
# ⡏⠀⠀⠀⠀⠀⠈⢺⣷⣄⣴⠛⠃⠀⠀⠀⠀⠀⠀⠀⠀⠈⠁⠀⠀⠀⠀⠸⠇⠄⠀⢀⡵⢛⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⣿⢸⣿⣿⣿⣮⡳⣄⣠⡴⣞⡽⠛⡻⣟⢦⣀⣼⢁⡏⠀⠀⠀⣾⣿⣿⣿⣿⣿⢠⣿⣤⣤⣤⠸⣧⣤⣼⠇⠘⠿⣶⣿⡧⣭⣭⣽⣷⠀⢸⠀⠀⠀⣿
# ⡇⠀⠀⠀⠀⠀⠀⠉⠉⠉⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⠎⠀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⠀⣿⢸⣿⣿⣿⣿⡍⠲⠖⣺⣿⠰⣿⡗⢸⣵⢯⡏⣸⡇⠀⠀⠀⡟⢻⣿⣿⣿⣿⣤⣤⣤⣤⣤⣤⣤⣤⣤⢤⣿⣿⣿⣿⣧⣤⣭⣥⣴⣤⡼⠀⠀⠀⣿
# ⠧⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠴⠷⠶⠶⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠶⠶⠦⠿⠿⠿⠿⠿⠿⠿⠶⠶⠿⠷⠶⠶⠶⠾⠿⠾⠷⠿⠷⠶⠶⠶⠿⠾⠮⠿⠿⠿⠿⠿⠿⠿⠿⠿⠿⠶⠶⠶⠶⠶⠶⠶⠶⠶⠶⠶⠶⠶
#两个数据库都要配置,不然用不了!
spring:
  #MySQL
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nyanid?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: nyanid
    password: nyanid
  data:
    #Redis
    redis:
      host: localhost
      database: 0
      password: nyanid123
      port: 6379
      #邮件服务,必须配置!
  mail:
    host: smtp.yeah.net #SMTP 服务器地址
    port: 25 #SMTP 服务器端口
    username: bjdbjd@bjdbjd.net #邮箱名
    password: bjdbjd #邮箱密码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false

#服务器配置
server:
  port: 8080
  address: localhost

#NyanID配置
NyanidSetting:
  EnableCommand: true #是否启用控制台指令
  EnableUserRegister: true #是否启用用户注册
  # IP访问限制(仅适用于authserver)
  MAX_REQUESTS_PER_SECOND: 6 #IP访问频率限制
  TIME_FRAME_IN_MILLISECONDS: 9500 #IP访问时间间隔
  encryptionKey: | #用户密码加密密钥(改了过后就不要改了!)
    JSJna98sdb7DAGBUG
    gd87TAD87T8AGD8t6
    87D567S567D5578ds6
    7d57SDd76TS67DT786
    S78d678678S6786cvg3
    cf4gfv67T6DSGVUhguGU
    YGgduysgUY34HJV2JH3
    4GGduygDTTS8F9Tgd5
    64EDW65F6WER54T6541
    SDF4EW6T541S33d1f3w
    e464464FG64WE6R54G3
    214T1S1AF454654ge4r6
    4FEH4E498T32D4GSK43
  HOST: "http://nyanid.cn:8080" #前端域名,注册时候发给用户验证邮件需要使用,因为API服务器需要隐藏真实IP,后端会默认给链接后面加上/verification/,所以链接后面不需要带 /
  qqbot:
    isEnable: false
    appid: "qqqqq"
    token: "qqqqqqqq"
    secret: "qqqqqqq"
    isSandbox: true
  ContactEmail: "neko@nyacat.cloud" #邮箱,用户收到邮件Contact us的邮箱地址
  TeamName: "DecObfNeko Development Team" #团队名称

#Minecraft 外置登录服务器配置
yggdrasil:
  implementationName: "yggdrasil-TakanashiHoshino-server"
  implementationVersion: "0.0.1"
  serverName: "TakanashiHoshino Server"
  links-homepage: "https://skin.example.com/"
  links-register: "https://skin.example.com/register"
  feature-non_email_login: true
  signaturePublickey: |
    -----BEGIN PUBLIC KEY-----
    MIICIj...（省略）...EAAQ==
    -----END PUBLIC KEY-----
    
